name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          use-pnpm: true

      - run: pnpm run eslint src/ --ext .tsx

      - run: pnpm run prettier --config .prettierrc 'src/**/*.tsx' --write

      - run: pnpm run build
